[build]
  command = "npm run build"
  publish = ".next"

# Allow Netlify Forms with Next.js
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Form handling
[build.processing]
  skip_processing = false
